server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: cslintern
    url: jdbc:postgresql://44.202.70.131:5432/test
    #this^ can only be run localy for now. Will change later when we figure out remote access
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: 
